version: '3.8'

services:
  db-app:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: db-app
    networks:
      app-net:
        ipv4_address: 172.0.10.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: mydb
    restart: unless-stopped

networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.10.0/24
