pipeline {
    agent any

    environment {
        SONAR_HOST_URL = 'http://sonarqube:9000'
    }

    stages {
        stage('checkout'){
            steps {
                checkout scm
            }
        }

        stage('SonarQube Analysis'){
            steps {
                withCredentials([string(credentialsId: 'TOKEN_SONAR', variable:'TOKEN']) {
                    sh """
                        echo "Running SonarQube analysis"
                    """
                }
            }
        }
    }
}