pipeline {
    agent any

    tools {
    nodejs 'Node-app'
}

    environment {
        SONAR_HOST_URL = 'http://localhost:9000'
    }

    stages {
        stage('checkout'){
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('app-front'){
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('app-front') {
                    sh 'npm test -- --watchAll=false'
                }
            }
        }

        stage('SonarQube Analysis'){
            steps {
                withCredentials([string(credentialsId: 'TOKEN_SONAR', variable:'TOKEN')]) {
                    sh """
                        cd app-front
                        npm test -- --watchAll=false
                                                sonar-scanner -X -Dsonar.token=$TOKEN -Dsonar.host.url=$SONAR_HOST_URL \
                        
                        """
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 1, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
}