# Copiar archivos desde el contexto del build (directorio raíz)
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .

# Etapa 2: Producción
#FROM node:20-alpine AS production

#WORKDIR /app

#COPY --from=builder /app .

EXPOSE 3000

CMD ["node", "server.js"]